Repository umass-cicsoft/umass-cicsoft.github.io, pull requests merged in 2022-01, with the labels that each got.

#29 Added gitignore and included .DS_Store
  .gitignore
Labels: enhancement

#24 Add media queries to make the headers on the landing page responsive
  assets/css/main.css
Labels: bug, enhancement

#19 Corrected vertical scaling issues on landing page to keep navigation bar visible at all times
  assets/css/main.css
  assets/img/brand-noBG.png
  assets/img/navbarLogo.png
  index.html
Labels: bug, enhancement

#32 Prepared remaining documentation for the website
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#41 Level the changes to resolve 3 interrelated issues
  assets/css/main.css
  assets/js/jquery.min.js
  assets/js/main.js
  assets/svg/Discord.svg
  assets/svg/Gmail.svg
  assets/svg/Instagram.svg
  index.html
Labels: documentation, enhancement

#42 Add the Team section to the website
  assets/css/main.css
  assets/img/team/404_her.jpg
  assets/img/team/404_him.jpg
  index.html
Labels: enhancement

#43 Add the Apply section to the website
  assets/css/main.css
  index.html
Labels: enhancement

#46 carousel slider added
  .DS_Store
  assets/.DS_Store
  assets/css/main.css
  assets/css/slider.css
  assets/img/.DS_Store
  assets/img/syllabus/0.png
  assets/img/syllabus/1.png
  assets/img/syllabus/2.png
  assets/img/syllabus/3.png
  assets/img/syllabus/4.png
  assets/img/syllabus/5.png
  assets/img/syllabus/6.png
  assets/img/syllabus/7.png
  assets/img/syllabus/8.png
  assets/js/jquery.min.js
  index.html
Labels: enhancement

#48 Normalize layout and styles
  .DS_Store
  assets/.DS_Store
  assets/css/main.css
  assets/css/slider.css
  assets/img/.DS_Store
  assets/img/team/anshul_vemulapalli.jpg
  assets/img/team/chandni_laheja.jpg
  assets/img/team/james_leone.jpg
  assets/img/team/kirat_arora.jpg
  assets/img/team/manmeet_singh_tuteja.jpg
  assets/img/team/rohan_raghuram.jpg
  assets/img/team/vansh_shah.jpg
  assets/js/main.js
  assets/svg/about_bg.svg
  index.html
Labels: enhancement

#50 Rebase public branch from main branch
  .DS_Store
  assets/.DS_Store
  assets/css/main.css
  assets/css/slider.css
  assets/img/syllabus/0.png
  assets/img/syllabus/1.png
  assets/img/syllabus/2.png
  assets/img/syllabus/3.png
  assets/img/syllabus/4.png
  assets/img/syllabus/5.png
  assets/img/syllabus/6.png
  assets/img/syllabus/7.png
  assets/img/syllabus/8.png
  assets/img/team/404_her.jpg
  assets/img/team/404_him.jpg
  assets/img/team/aditya_vikram_singh.jpg
  assets/img/team/anshul_vemulapalli.jpg
  assets/img/team/anushree_patil.jpg
  assets/img/team/chandni_laheja.jpg
  assets/img/team/james_leone.jpg
  assets/img/team/kirat_arora.jpg
  assets/img/team/manmeet_singh_tuteja.jpg
  assets/img/team/prit_shah.jpg
  assets/img/team/rohan_raghuram.jpg
  assets/img/team/siddharth_jain.jpg
  assets/img/team/vansh_shah.jpg
  assets/js/jquery.min.js
  assets/js/main.js
  assets/svg/Discord.svg
  assets/svg/Gmail.svg
  assets/svg/Instagram.svg
  index.html
Labels: enhancement
